apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: app
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      nodeSelector:
        role: service
      containers:
        - name: admin-service
          image: 295234319852.dkr.ecr.ap-northeast-2.amazonaws.com/maesoongan/admin-service:bbb762665860a290058e1795d78aebebbb74b4e0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ADMIN_SERVICE_PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: maesoongan-api-config
            - secretRef:
                name: maesoongan-api-secret
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: app
  labels:
    app: admin-service
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
