apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: app
  annotations:
    configmap.reloader.stakater.com/reload: maesoongan-api-config
    secret.reloader.stakater.com/reload: admin-service-secret
  labels:
    app: admin-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"

      labels:
        app: admin-service
    spec:
      nodeSelector:
        role: service
      containers:
        - name: admin-service
          image: 295234319852.dkr.ecr.ap-northeast-2.amazonaws.com/maesoongan/admin-service:0022d9ad94552102758386c10e6dee82aa1e10bf
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ADMIN_SERVICE_PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: maesoongan-api-config
            - secretRef:
                name: admin-service-secret
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: app
  labels:
    app: admin-service
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
