apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-service-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: admin-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/admin-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: auth-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/auth-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: contest-service-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: contest-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/contest-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: market-service-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: market-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/market-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: order-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/order-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-api-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: notification-api-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/notification-api
