apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: app
  annotations:
    configmap.reloader.stakater.com/reload: maesoongan-api-config
    secret.reloader.stakater.com/reload: order-service-secret
  labels:
    app: order-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8084"
      labels:
        app: order-service
    spec:
      nodeSelector:
        role: service
      containers:
        - name: order-service
          image: 295234319852.dkr.ecr.ap-northeast-2.amazonaws.com/maesoongan/order-service:0056e1f26c91aa450046721d7faf93d5df0d1309
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: ORDER_SERVICE_PORT
              value: "8084"
          envFrom:
            - configMapRef:
                name: maesoongan-api-config
            - secretRef:
                name: order-service-secret
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: app
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
