apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secret
  namespace: app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: REPLACE_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: REPLACE_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: REPLACE_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: REPLACE_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: REPLACE_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: REPLACE_DATASOURCE_PASSWORD
  APP_JWT_SECRET: REPLACE_APP_JWT_SECRET
  REDIS_HOST: REPLACE_REDIS_HOST
  REDIS_PASSWORD: REPLACE_REDIS_PASSWORD
  SPRING_MAIL_USERNAME: REPLACE_MAIL_USERNAME
  SPRING_MAIL_PASSWORD: REPLACE_MAIL_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: contest-service-secret
  namespace: app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: REPLACE_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: REPLACE_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: REPLACE_DATASOURCE_PASSWORD
  APP_JWT_SECRET: REPLACE_APP_JWT_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: market-service-secret
  namespace: app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: REPLACE_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: REPLACE_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: REPLACE_DATASOURCE_PASSWORD
  APP_JWT_SECRET: REPLACE_APP_JWT_SECRET
  KIS_APP_KEY: REPLACE_KIS_APP_KEY
  KIS_APP_SECRET: REPLACE_KIS_APP_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: REPLACE_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: REPLACE_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: REPLACE_DATASOURCE_PASSWORD
  APP_JWT_SECRET: REPLACE_APP_JWT_SECRET
  REDIS_HOST: REPLACE_REDIS_HOST
  REDIS_PASSWORD: REPLACE_REDIS_PASSWORD
  KIS_APP_KEY: REPLACE_KIS_APP_KEY
  KIS_APP_SECRET: REPLACE_KIS_APP_SECRET
  KIS_ACCOUNT_NUMBER: REPLACE_KIS_ACCOUNT_NUMBER
---
apiVersion: v1
kind: Secret
metadata:
  name: market-realtime-service-secret
  namespace: app
type: Opaque
stringData:
  REDIS_HOST: REPLACE_REDIS_HOST
  REDIS_PASSWORD: REPLACE_REDIS_PASSWORD
  KIS_APP_KEY: REPLACE_KIS_APP_KEY
  KIS_APP_SECRET: REPLACE_KIS_APP_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: user-realtime-service-secret
  namespace: app
type: Opaque
stringData:
  APP_JWT_SECRET: REPLACE_APP_JWT_SECRET
