apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: market-realtime-service-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: market-realtime-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/market-realtime-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-realtime-service-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: user-realtime-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/user-realtime-service
