apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trade-sync-worker-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maesoongan-aws-secrets
  target:
    name: trade-sync-worker-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: maesoongan/prod/trade-sync-worker
