apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maesoongan-worker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MaeSoonGan/Back-End.git
    targetRevision: develop
    path: infra/k8s/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
